### ISSUE TITLE
Can't find the tickbox for Bing/Here/Open Street Map and others

### ISSUE THREAD

**Issue by YanisKyr** [WazeDev/WME-Open-Other-Maps#26]
This is all I see:
![OOM](https://i.imgur.com/zgue8Ox.png)

**Comment by justins83** [comment]
Yes, they were removed at the request of Waze staff because they are not allowed to be used due to copyright issues.

**Comment by YanisKyr** [comment]
Thanks Justin. Might be a good idea to update the descriptions of the script then?

Mind me asking what was the last version that included these options?
